### ISSUE TITLE
New category 

### ISSUE THREAD

**Issue by lukasz-madon** [lukasz-madon/awesome-remote-job#106]
Any proposition for a new category for:

http://www.thecaravanserai.co/
http://www.hackerparadise.org/

Hacker space?

**Comment by RichardLitt** [comment]
Hacker spaces doesn't quite cut it. Providing a list of hackerspaces in popular cities - where you can work remotely - might be a good idea. For instance, I'm currently in [Noisebridge](https://www.noisebridge.net) in SF. Maybe we could do that, have location subsections, and then have a _Global_ subsection for the two you mention?

**Comment by tedder** [comment]
It's probably worth pointing to this list: http://hackerspaces.org/wiki/List_of_Hacker_Spaces

No need to pretend to be canonical on everything.

**Comment by AlexeyMK** [comment]
:+1:

**Comment by AlexeyMK** [comment]
We at Hacker Paradise have been calling ourselves a "traveling hacker community" which isn't quite what Caravaneserai is and is closest, perhaps, to what the http://www.remoteyear.com/ folks are doing (but they're more intense).

Category name ideas: Organized Workaway Communities, Remote Coliving, perhaps?

**Comment by Campbellb** [comment]
The
On Feb 9, 2015 4:05 PM, "Ted Timmons" <notifications@github.com> wrote:
>
> It's probably worth pointing to this list:
http://hackerspaces.org/wiki/List_of_Hacker_Spaces
