### ISSUE TITLE
Include sites for people hosting in exchange of skills

### ISSUE THREAD

**Issue by rafaecheve** [lukasz-madon/awesome-remote-job#123]
https://www.worldpackers.com

**Comment by lukasz-madon** [comment]
hmm. Separate section?

**Comment by rafaecheve** [comment]
maybe, what do the people say? I think for now a separate section will make it

**Comment by robertbenjamin** [comment]
I think it'd be a good decision! The point of remote jobs (for the most place) is locational freedom, jobs on Worldpackers (and HelpX, WWOOF, etc) give you that freedom since you can choose where and who to work for.

**Comment by tedder** [comment]
I'm good with it, there's certainly a subset of "working remote while roaming the world" type people. Some of the things on "Others" like nomadlist could move to that category.

I'll reorganize some of them in a PR if it's desired.

**Comment by rafaecheve** [comment]
any suggestions for the section naming welcome!

**Comment by robertbenjamin** [comment]
Maybe 'Work / Housing Exchange?' ['Hospitality Service'](http://en.wikipedia.org/wiki/Hospitality_service) is what it's officially called.

**Comment by tedder** [comment]
sure, but it's more than "housing exchange". I kinda like "digital nomads" or something that covers more ground.

**Comment by robertbenjamin** [comment]
Most of the opportunities on these sites aren't digital work, they're typical light physical housework or teaching a language / skill. I don't know of any site that lets you work online in exchange for housing, although that would be really cool.

**Comment by bzz** [comment]
Are there other examples that fit in the suggested category? We could deduce a better name from that

**Comment by robertbenjamin** [comment]
The most popular ones are HelpX, WWOOF, Worldpackers, Workaway, Global Exchange.

**Comment by bzz** [comment]
as #125 was merged ```Work / Housing Exchange``` how it is called now. 
Sounds good but a bit confusing at the first sight.. 

May be ```Work in exchange for Housing```?

thanks @robertbenjamin ! Should we include those too? At least WWOOF looks pretty awesome

**Comment by robertbenjamin** [comment]
I'd definitely add WWOOF and HelpX, there are a ton of crazy cool opportunities on there if you look carefully!

**Comment by RichardLitt** [comment]
We now have a housing section. Thanks, all.
