### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by arthurvr** [lukasz-madon/awesome-remote-job#175]
This repo seems to miss a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by lukasz-madon** [comment]
:+1:

**Comment by RichardLitt** [comment]
@lukasz-madon I'll just add the same license: cc0, if that works for you.

**Comment by lukasz-madon** [comment]
@RichardLitt 👍 👍 👍
