### ISSUE TITLE
DataStax is not a consulting company, it is a software company

### ISSUE THREAD

**Issue by pkolaczk** [lukasz-madon/awesome-remote-job#178]
DataStax delivers Apache Cassandra™ in a database platform that meets the performance and availability demands of Internet-of-things (IoT), Web, and Mobile applications. It gives enterprises a secure, fast, always-on database that remains operationally simple when scaled in a single datacenter or across multiple datacenters and clouds.

**Comment by tedder** [comment]
is that your suggestion for text? It's very.. markety. Currently it says "Consulting based on Apache Cassandra.". Perhaps it should say "Apache Cassandra provider"? "Apache Cassandra service"?

**Comment by mattc58** [comment]
Maybe "Database platform software based on Apache Cassandra. Developers work remotely from around the world, working in Java, Clojure, Python, and JavaScript."?

**Comment by pkolaczk** [comment]
Looks good.

**Comment by lukasz-madon** [comment]
See CONTRIBUTING.md examples.
