### ISSUE TITLE
Video / video blog / blogs with photos

### ISSUE THREAD

**Issue by rpCal** [lukasz-madon/awesome-remote-job#183]
Hi, 
I was wondering is there any video blogs about remote job? Maybe some developers who working remote have video blog or podcast or even maybe blog with nice photos?
Sory if questions was asked but I didnt see any similar question.

ps. pls add this link to video section if any one have some free time(I dont have it now) 
[RedDotRuby 2015 - Working Remotely as a Junior Developer by Laura Eck]  ( https://www.youtube.com/watch?v=XdFY-zpT4JY) - nice overview of remote working for junior developer.

**Comment by lukasz-madon** [comment]
fee free to make a PR
