### ISSUE TITLE
Provide section about cellphone simcards

### ISSUE THREAD

**Issue by giampaolo** [lukasz-madon/awesome-remote-job#251]
It would be good to have a list of convenient SIM cards/contracts providing a reasonably fast and cheap internet connection sorted by country.

**Comment by lukasz-madon** [comment]
A whole list would be quite large, so it could be a link to a separate list.

**Comment by RichardLitt** [comment]
Agreed. Feel free to PR with a link to such a list - this is well out of our scope.

**Comment by jeverling** [comment]
I found this wiki quite helpful when I was in Brazil: http://prepaid-data-sim-card.wikia.com/wiki/Prepaid_SIM_with_data
