### ISSUE TITLE
Europe Remotely

### ISSUE THREAD

**Issue by reclaimer** [lukasz-madon/awesome-remote-job#312]
Couldn't find [Europe Remotely](http://europeremotely.com) in the list. Is it ok to add?

**Comment by IvanJov** [comment]
@reclaimer Europe Remotely is not maintained any more :(

**Comment by RichardLitt** [comment]
Yep. Reopen if he reopens it.

**Comment by IvanJov** [comment]
Reopening this issue. Europe Remotely is working again! I've sent PR!

**Comment by IvanJov** [comment]
@RichardLitt You can close this one too!
