### ISSUE TITLE
75. Railsdog / company's domain expired  

### ISSUE THREAD

**Issue by chubbypanda** [lukasz-madon/awesome-remote-job#314]
Given address http://railsdog.com shows GoDaddy's parking page. Their last tweet (https://twitter.com/railsdog) is from October 2015. Should be entry 75 deleted or perhaps moved into a new section called 'inactive companies'?

**Comment by lukasz-madon** [comment]
If the company is closed deleting is the best option.

**Comment by chubbypanda** [comment]
Thanks, good to know. Deleted already.
