### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by RichardLitt** [lukasz-madon/awesome-remote-job#334]
Hey Lukasz; tried your email from your GitHub profile, and it bounced. There's a few open PRs - do you need help maintaining this list?

**Comment by lechuckcaptain** [comment]
I would love to help too. Maybe a **Support** chapter on the Readme would be a good idea.

**Comment by lukasz-madon** [comment]
Github email is a tiny riddle ;)

I have disabled notification for PRs for this repository, because there were too many at some point.

**Comment by RichardLitt** [comment]
Heh. I failed, then. Hopefully I can help with the PRs. :)
