### ISSUE TITLE
Add coveralls.io in companies list with remote DNA

### ISSUE THREAD

**Issue by fakiolinho** [lukasz-madon/awesome-remote-job#347]
You can add [coveralls.io](https://coveralls.io/careers) in companies list with remote DNA

**Comment by RichardLitt** [comment]
Pinged them on Twitter. I don't see a mention of remoteness on their website anywhere, but no location either. Would be great to get a clarification from the team.

**Comment by fakiolinho** [comment]
Hmmm, yes not 100% sure so i also sent an email and asked them to verify here.

**Comment by nickmerwin** [comment]
Hi @fakiolinho and @RichardLitt, we are!

My co-founder @anjin and I both live in Los Angeles, but only work remotely.

Thank you for the shout-out on this list!

**Comment by RichardLitt** [comment]
Thank you, @nickmerwin! Added to the list.
