### ISSUE TITLE
Website of [Casa98] in Medellin, Colombia doesn't work

### ISSUE THREAD

**Issue by teinett** [lukasz-madon/awesome-remote-job#366]
NOW: [Casa98](http://casa98.co/) - Coworking space. Medellin, Colombia
REALITY: there is an e-shop website on this URL.

I suggest to delete this place or find the proper one.

**Comment by RichardLitt** [comment]
Thanks @teinett! Would you like to submit a PR? :)

**Comment by teinett** [comment]
@RichardLitt I tried to fix it but failed. Please, change it?

**Comment by RichardLitt** [comment]
Done. Thanks!
