### ISSUE TITLE
Companies and Countries

### ISSUE THREAD

**Issue by bueltge** [lukasz-madon/awesome-remote-job#395]
The part of the Companies with "remote DNA" should sort according to different countries. Yes, it is remote, but it is also a part for the law and contracts to search for a company in different countries.

What do you think, is it helpful?

**Comment by RichardLitt** [comment]
If you'd like to help do that, sure. I find it a bit ironic, as remote often means it isn't location dependent. But there are some practicalities which make it worth having sorted for this.

I think another option would be just to include, in parens, the nation where a company is from. 

> 93. Maintainer Mountaineer - Open source community management as a service. (USA)

What do you think?

**Comment by bueltge** [comment]
Yes, that is what I mean, it is a bit ironic in this context. But often search employees for jobs only in different countries.  Your idea is also helpful, yes. Also easier to add this company is from. Also, maybe, we have the problem, that different companies have different locations - we should use the main location.

**Comment by RichardLitt** [comment]
Or you could use multiple locations. PRs accepted. :)

**Comment by dougaitken** [comment]
Related to this, this actually part of a list I maintain - https://github.com/remoteintech/remote-jobs - would be awesome (heh) if I could include this somehow, or move the companies from here into my list and have one list to update?

**Comment by RichardLitt** [comment]
That's interesting - that's a very similar list. In my opinion, moving our list of remote companies out of this list would not be ideal, because it's a large part of our content. Cross linking would be possible, for sure. 

Another option which is kinder to both of us (in terms of prestige, aka stars) would be to use a third repository as the data, and then build scripts that automatically PR to each other's repos from that list. But that's pretty high overhead, and it'll make submitting to each repo a bit harder. 

Going to have to ask @lukasz-madon what he thinks.

**Comment by lukasz-madon** [comment]
@dougaitken I added you as a collaborator. I'd great if you could merge your list without duplicates into ours - that should be 10 lines of python :). The only reason is that this one is more popular. 

> Another option which is kinder to both of us (in terms of prestige, aka stars) would be to use a third repository as the data, and then build scripts that automatically PR to each other's repos from that list. But that's pretty high overhead, and it'll make submitting to each repo a bit harder.

That's too much hassle IMO.

**Comment by bueltge** [comment]
Great, that the idea will fly. I have not enough time currently for PR. Thanks @dougaitken

**Comment by dougaitken** [comment]
Hi all, 

Thanks for the comments @RichardLitt @lukasz-madon !

> that should be 10 lines of python

heh. all good if you know Python :P 

Thinking about this more, this repository is what I'd like to see overall for my list, but in a different angle. I'm going to have a "front end" to the list to make it searchable, and then have advice along with that on the main `https://remoteintech.company` site. Basically "here is a list of companies who hire remotely that you can search, and here is a blog with some advice as well".

Very happy to collaborate to improve both of our lists!

**Comment by RichardLitt** [comment]
I'm going to close this as stale. Thanks, all. @dougaitken Feel free to make a PR to add content to this list; @bueltge Feel free to sort the companies. However, as we haven't had any updates on this for a while, I am assuming that this work won't get done for now, which is also OK.
