### ISSUE TITLE
Disallow self-posts

### ISSUE THREAD

**Issue by RichardLitt** [lukasz-madon/awesome-remote-job#419]
I don't think that you can judge objectively whether your own app or site is awesome. We get a lot of self posts, and I feel weird merging them. I want to add a line to the contribute saying don't self-post your own product. What do you think, @lukasz-madon?

**Comment by lukasz-madon** [comment]
I don't think the self-post is bad and it's trivial to work around it get some free marketing even if your tool is crap. I'm working remotely and occasionally try them out. If it's bad/doesn't exist anymore I'll delete it.
