### ISSUE TITLE
Remove all job boards

### ISSUE THREAD

**Issue by RichardLitt** [lukasz-madon/awesome-remote-job#578]
Can we just remove them all, and stop accepting new ones? It would solve the quality problems for PRs we keep getting, @lukasz-madon.

**Comment by lukasz-madon** [comment]
Good question, some of them are good. We can stop accepting new ones, unless there is a really good reason for it.

**Comment by RichardLitt** [comment]
@lukasz-madon 	Sweet. Added a note to the contributing.
