### ISSUE TITLE
Remote Teams: An open list of companies with Distributed Remote Teams.

### ISSUE THREAD

**Issue by brajeshwar** [lukasz-madon/awesome-remote-job#58]
I wanted to add a reference to a curated list that I started sometime back.
I'm not sure which heading I should add that!

http://oinam.github.io/remote-teams/

**Comment by waldyrious** [comment]
Isn't that list somewhat duplicated in the *Companies with "remote DNA"* heading? Have you considered joining forces? Your site looks really neat :)

**Comment by brajeshwar** [comment]
Good Idea. If @lukasz-madon likes the idea, I can help convert this into a more beautifully maintained site, even if we have to stick to just Markdown.

**Comment by lukasz-madon** [comment]
Looks neat, but I can't find the reason for html. Markdown is sweet, short and gets the job done.

I'll appreciate if could make PR without duplicates.

**Comment by waldyrious** [comment]
@lukasz-madon if, as @brajeshwar mentioned, github pages can be made to work using just markdown, would that be acceptable?

@brajeshwar let me know if I can be of any help in preparing the PR :)

**Comment by lukasz-madon** [comment]
I playing around with a jobs scraper that will be in gh-pages branch. It would need some :heart: more than the list.
