### ISSUE TITLE
List all job posts

### ISSUE THREAD

**Issue by lukasz-madon** [lukasz-madon/awesome-remote-job#60]
I made an example page with job posts @waldyrious @brajeshwar

http://lukasz-madon.github.io/awesome-remote-job/

It uses AngularJS to talk to KimonoLabs scraping api. I welcome any suggestions.

**Comment by waldyrious** [comment]
Looks very nice so far :) Do you plan to have it show the rest of the resources, or just the jobs?

**Comment by lukasz-madon** [comment]
I'm thinking about job posts for now. Kimono is nice but it maybe hard to build the scraper and you can't make a PR to fix a broken scraper.

**Comment by waldyrious** [comment]
I see. It's a pity that the whole package wouldn't be cohesive though. How about having separate pages, generated from markdown files, and using the same visual style? Then instead of a single page with the job list, we'd have a mini-site with one page for each kind of resource currently collected in the README.md, and the ease of contribution (markdown files) would remain in place :)

**Comment by lukasz-madon** [comment]
how would you build it? if I update readme will the website update as well?

**Comment by waldyrious** [comment]
I've only read lightly about Jekyll, which I suspect is the easiest way to do it. I'll let @brajeshwar make a more informed comment, since (unlike me) he seems to actually know what he's talking about :-)

**Comment by brajeshwar** [comment]
Jekyll is pretty straight forward as Github Pages runs on Jekyll. In my case, I'm just feeding a ```yml``` file for the data. That way, it is easier for others to contribute just at the data point and not worry about the HTML and/or Markup. :-)

**Comment by lukasz-madon** [comment]
It's not exactly clear how it's going to work. Someone sends me a PR and I check & merge. Then what happens? I like to avoid updating data in two places.

If this is going to be automated then I'm up for it.

**Comment by brajeshwar** [comment]
You'll still need to review the PR that someone send but now, you'll have to just worry about the data. The presentation (Jekyll) is something people won't have to worry about.

I'm pretty sure you'll still have to do the PR when someone sends one to your Markdown.

**Comment by waldyrious** [comment]
@brajeshwar can you expand a little on what you mean by "you'll still have to do the PR"?

**Comment by brajeshwar** [comment]
I was trying to mean the Pull Request which is we typically would do on Github.
https://help.github.com/articles/using-pull-requests/

**Comment by RichardLitt** [comment]
Sure; but how is that data updated automatically?

**Comment by waldyrious** [comment]
I'm particularly confused about whether it would have to be a separate PR from, in your words, "the PR that someone send" with changes to the markdown document. Can you describe step-by-step how the process would work?

**Comment by brajeshwar** [comment]
Well, I don't see any automatic updates happening anywhere. Someone with new contents to the data send a PR just for that, the owner/collaborators reviews it and if good, merge the PR.

I think I'm missing something somewhere in your discussion.

**Comment by stargazer33** [comment]
The idea to use KimonoLabs scraping api is awesome )))
For some sites this will be the only way to get data.

But. For ***many*** site (specially for job boards) we can use RSS or ATOM.
Examples:
http://careers.stackoverflow.com/jobs/feed?allowsremote=True
http://www.authenticjobs.com/rss/custom.php?terms=&type=1,3,5,2,6&cats=&onlyremote=1&location=
https://zapier.com/engine/rss/242783/frontenddevjob
http://itflow.biz/?feed=job_feed&type=contract,freelance,full-time,part-time,temporary&location&job_categories&s&job_region=2430
http://www.jobbox.io/offers.atom?t=&s=&r=on
https://weworkremotely.com/categories/2/jobs.rss

This way we get structured information without any scraping. I think, there should be a way to load RSS/ATOM in browser.... (I'm not a Javascript expert)

**Comment by lukasz-madon** [comment]
Awesome.

I'm swamped with work and other stuff right now. I only have time to review PR :shipit:

**Comment by stargazer33** [comment]
Hi everybody,

here the server-side command-line approach to deal with many job boards listed here: 
https://github.com/stargazer33/rss-filter

works for me quite well. 
For your specific job search you would need specific config.yml

**Comment by douglascorrea** [comment]
Why not use github issues as job posting? 
This is used very well here: https://github.com/frontendbr/vagas/issues

And I think we could use it here, posting remote job opportunities as github issues of this repo (or create another one specific for it).

**Comment by lukasz-madon** [comment]
@douglascorrea that's a good idea.

**Comment by karllhughes** [comment]
Just curious if you guys have made any progress on scraping/aggregating content? It's something I'd like to do for my OSS org JobApis.com, but if there's a good start on this I'd rather help than start over.

**Comment by RichardLitt** [comment]
I think we should close this idea as stale. I'm not sure we're going to get to it, and I think it's not necessary for the list to be awesome. :)

**Comment by waldyrious** [comment]
Agreed @RichardLitt. That said, if anyone wants to contribute an implementation that would be low-maintenance (especially if it would be hosted via GitHub Pages, rather than requiring a separate server), it would be very welcome!
