### ISSUE TITLE
Add https://github.com/remote-es/remotes

### ISSUE THREAD

**Issue by alexpdp7** [lukasz-madon/awesome-remote-job#627]
Hi,

We keep a list of companies offering remote jobs *in Spain* (so Spanish people can work there with a full-time contract; working for foreign companies remotely has significant issues) at:

https://github.com/remote-es/remotes

I'm not entirely sure which category should this be added to- or even if it fits the repo. If you give me some pointers I can send a PR.

Cheers,

Álex

**Comment by RichardLitt** [comment]
Probably in the Job Boards section. Go ahead and add it. Thanks! :)

**Comment by alexpdp7** [comment]
https://github.com/lukasz-madon/awesome-remote-job/pull/636
