### ISSUE TITLE
PRs failing because of previous dead links

### ISSUE THREAD

**Issue by vishalkdotcom** [lukasz-madon/awesome-remote-job#646]
The builds are failing due to some of the previous dead links.
Atleast, the below PRs failed because of this:
#643
#644 
#645  

Here is the one of the snapshot of the build errors:
![image](https://user-images.githubusercontent.com/342746/81477050-1ca84a80-9233-11ea-84a1-41cb60906492.png)

https://travis-ci.org/github/lukasz-madon/awesome-remote-job/builds/684529004

I manually checked, the links mentioned in the build snapshot are really dead.

Please let me know, if I should raise a new PR to add kaamwork or any additional step required.
Thanks!

**Comment by RichardLitt** [comment]
Thanks for checking. I noticed that, too, and fixed the links [yesterday.](https://github.com/lukasz-madon/awesome-remote-job/commits/master). Appreciate the extra effort, though!
