### ISSUE TITLE
README structure - companies

### ISSUE THREAD

**Issue by lukasz-madon** [lukasz-madon/awesome-remote-job#69]
How to structure companies list? There is an example of a company that doesn't have a career page #61 

I decided to link to careers page since there is a place where remote work is described.

**Comment by waldyrious** [comment]
IMHO: The list is of companies with "remote DNA", not companies currently hiring remote workers (none of them will be permanently hiring, anyway). So while it makes sense to make it a guideline / default pattern to link to the career page (which is where they usually describe their remote-friendliness), occasional exceptions should be fine, I guess. It might be nice if they had an "about" or "team" page, however, where they make it clear that it's a remote team. Maybe you could have that as a second-choice requirement for inclusion in the README.

You know what would be even nice? If we had a "remote.friendly" badge (perhaps even adopting the visual language that [shields.io](https://github.com/badges/shields#problem) has proposing as a standard) which companies could have anywhere on their website, and they could then just link to their home page if they don't have a careers one, as long as the badge is visible, say in the footer or something. (I literally just thought of this; what do you think?)

**Comment by waldyrious** [comment]
@joshuap you might want to comment here :)

**Comment by RichardLitt** [comment]
I also think that not having a careers page shouldn't be a disqualifier for listing, especially as in my experience the best jobs are gotten by developers looking for work at a specific company even if there isn't a job opening. A remote friendly badge would solve the issue for companies that don't have career pages that enable easy linking, though.

**Comment by achanda** [comment]
How about having a different section for companies which allow remote workers but are not hiring now? It should be easy to move entries between sections.

**Comment by lukasz-madon** [comment]
Agreed. I merged Honeybadger and removed "Currently Hiring".

I love the idea of badges what is even better is a ribbon https://github.com/blog/273-github-ribbons
It could be on the main page without damaging the layout. :+1:

**Comment by joshuap** [comment]
I think this is a great project and am all for advancing companies with remote DNA. A shields.io-style badge seems more reasonable to me than a ribbon because a very small percentage of visitors to our homepage are looking for work with us, so a ribbon feels like a disproportionate amount of attention. The badge on the other hand is something which many of us are already comfortable with and use on a regular basis. In fact, @olivierlacan might be able to say if this would be a good use-case.

Of course, you could always do both -- let people choose how much they want to promote the project with a few options. :)

**Comment by lukasz-madon** [comment]
@joshuap I already made one http://lukasz-madon.github.io/awesome-remote-job/

I could stick it to homepage if you really care about promoting remote work e.g. Basecamp. Otherwise just stick it to careers page.
