### ISSUE TITLE
Remote Friendly Ribbon

### ISSUE THREAD

**Issue by lukasz-madon** [lukasz-madon/awesome-remote-job#71]
@waldyrious had an excellent idea to make a badge similar to http://shields.io/. Here is my take on it.

Ribbon with markup http://lukasz-madon.github.io/awesome-remote-job/

**Comment by lukasz-madon** [comment]
Badge is also great.

![Why not both?](http://i.imgur.com/c7NJRa2.gif)

**Comment by RichardLitt** [comment]
Cool ribbon. Not sure who would use it. But no harm making it.

**Comment by waldyrious** [comment]
I think we should have both, especially since the ribbon might be a little too attention-grabbing.
