### ISSUE TITLE
Nonprofit Remote - violates contributing rule 1

### ISSUE THREAD

**Issue by Shatnerz** [lukasz-madon/awesome-remote-job#726]
[Nonprofit Remote](https://nonprofitremote.com/) - A place where remote workers, volunteers, and nonprofits connect.

This link has a majority, if not all, jobs hidden behind a $7/month paywall requring sign-in. This validates the first contributing rule. Please consider removing.

"""

1. Job boards should be high quality, **without paywalls, requiring login, etc.**

"""

**Comment by RichardLitt** [comment]
Thanks. Removed.
