### ISSUE TITLE
"We Love Go" should be removed, it is a AD website now

### ISSUE THREAD

**Issue by Linde7777** [lukasz-madon/awesome-remote-job#897]

**Comment by aman-trunksaiden69** [comment]
provide the screenshot or some description

**Comment by aman-trunksaiden69** [comment]
@Linde7777 it is showing me exact same thing, but i will try my best to open it.

**Comment by Technetium1** [comment]
![image](https://github.com/user-attachments/assets/c8224f3a-c736-4962-8c81-1199703400bc)
![image](https://github.com/user-attachments/assets/c14bf93a-391c-42b4-af80-d87ca54dd64e)
Every visit redirects to some new ad garbage.
