### ISSUE TITLE
awesome_bot needs to do clean up on main branch

### ISSUE THREAD

**Issue by sharktrexer** [lukasz-madon/awesome-remote-job#902]
On other people's PRs I am seeing that awesome_bot is labeling some urls as dead that aren't related to their changes. Awesome_bot seems to create a readme with new changes in the github action but doesn't implement them.

Should a PR be done to remove those links? I could write a quick script to do so or install and run awesome_bot on a fork of the repo and do a PR from there. 

What are your thoughts?

**Comment by RichardLitt** [comment]
Make a PR, then at me. Thanks.

**Comment by sharktrexer** [comment]
Will do 👍
